[package]
name = "sewup"
version = "0.0.1"
authors = ["Antonio Yang <yanganto@gmail.com>"]
edition = "2018"
build="build.rs"

[dependencies]
thiserror = "1.0.24"
anyhow = "1.0.40"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5.8"
ethereum-types = {features = ["serialize"], git = "https://github.com/paritytech/parity-common.git", rev = "0867e488f6567e0d7fe13e78a14797ff019033f7" }
evmc-sys = { git = "https://github.com/second-state/evmc", tag = "v7.4.0-rust-evmc-client-rc.2" }

[dev-dependencies]
tempfile = "3.2.0"
rust-ssvm = { git = "https://github.com/second-state/rust-ssvm.git", rev = "5b37140a2e573aef62dde6a68003b1d51faeef77" }

[build-dependencies]
cmake = "0.1.42"

[features]
default = []
token = []
