[workspace]

members = [
    "sewup",
    "sewup-derive",
]
exclude = [
    "examples/hello-contract",
    "examples/default-contract",
    "examples/erc20-contract",
    "examples/kv-contract",
    "examples/rusty-contract",
]
