[package]
name = "sewup-derive"
version = "0.1.0"
authors = ["Antonio Yang <yanganto@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
regex = "1"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[dev-dependencies]
hex-literal = "0.3.1"
