name: CI

on:
  push:
    branches: [ debug ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Clippy
        env:
          RUST_BACKTRACE: full
        run: nix-shell --run "rustc --version --verbose && cargo clippy"

      - name: Test
        run: nix-shell --run "cargo test --all-features"
