name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Super-Linter
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_RUST_2018: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # - name: Clippy
      #   env:
      #     RUST_BACKTRACE: full
      #   run: nix-shell --run "rustc --version --verbose && cargo clippy"

      - name: Token feature test
        run: nix-shell --run "run-test token"

      - name: Token feature test
        run: nix-shell --run 'run-test kv || echo -e "\e[38;5;196m\e[0m allow fail"'
