name: Cli

concurrency:
  group: cli-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  default-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Init default project test
        run: nix develop -c 'cli-init-test' default

      - name: Init rusty project test
        run: nix develop -c 'cli-init-test' rusty

      - name: Init auto project test
        run: nix develop -c 'cli-init-test' auto
