name: Crate

concurrency:
  group: crate-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_RUST_2018: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Remove non-nix binary
        run: rm -rf ~/.cargo/bin

      - name: Clippy sewup
        run: nix develop -c cargo clippy -p sewup
        env:
          RUST_BACKTRACE: 1

      - name: Default feature test
        run: nix develop -c cargo test -p sewup --features=default

      - name: RDB feature test
        run: nix develop -c cargo test -p sewup --features=rdb --no-default-features

      - name: Token feature test
        run: nix develop -c cargo test -p sewup --features=token --no-default-features

      - name: KV feature test
        run: nix develop -c cargo test -p sewup --features=kv --no-default-features

      # TODO Fix me when test ready
      - name: Build Single bucket feature
        run: nix develop -c cargo build -p sewup --features=single-bucket --no-default-features
