name: Doc
on:
  push:
    branches: [ main, doc ]

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: experimental-features = nix-command flakes

      - name: Build Native Documentation
        run: nix develop -c 'cargo' doc -p sewup -p sewup-derive --all-features

      - name: Build Wasm Documentation
        run: nix develop -c 'cargo' doc -p sewup -p sewup-derive --all-features --target=wasm32-unknown-unknown

      - name: Deploy Documentation
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/doc
          SCRIPT_MODE: true
        run: |
          wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.5.0/entrypoint.sh
          bash ./entrypoint.sh
