name: Doc
on:
  push:
    branches: [ main ]

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Documentation
        run: nix-shell --run "cargo doc -p sewup --features=kv"

      - name: Deploy Documentation
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/doc
          SCRIPT_MODE: true
        run: |
          wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.5.0/entrypoint.sh
          bash ./entrypoint.sh
