name: Example

concurrency:
  group: erc721-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  erc721-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run test
        run: nix develop -c 'run-example-test' erc721

      - name: Deploy test
        run: nix develop -c 'cli-build-test' erc721

      - name: ABI test
        run: nix develop -c 'abi-test' erc721
