name: Rust Crate Release

concurrency:
  group: rust-crate-release-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  crate_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Default feature test
        run: nix develop -c 'cargo' test -p sewup

      - name: Publish cargo-sewup crate
        run: nix develop -c 'crate-publish' cargo-sewup ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish sewup-derive crate
        run: nix develop -c 'crate-publish' sewup-derive ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Prepare sewup crate
        run: |
          VERSION=`cat sewup-derive/Cargo.toml | grep '^version' | awk -F\" '{print $2}'`
          sed -i 's/sewup-derive =/sewup-derive = "'${VERSION}'"#/' sewup/Cargo.toml
          git config --global user.email "github_action@github.com"
          git config --global user.name "GithubAction"
          git add sewup/Cargo.toml
          git commit -m '[CI] update sewup dependency'

      - name: Publish sewup crate
        run: nix develop -c 'crate-publish' sewup ${{ secrets.CARGO_REGISTRY_TOKEN }}
