name: Typo
on:
  pull_request:

jobs:
  typo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05-small

      - name: Install typos
        run: nix-shell --run "cargo install typos-cli"

      - name: Check typo
        run: nix-shell --run "typos"
