name: Typo
on:
  pull_request:

jobs:
  typo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install typos
        run: nix develop -c 'cargo' install typos-cli

      - name: Check typo
        run: nix develop -c 'typos' --exclude ssvm-evmc
