[package]
name = "cargo-sewup"
version = "0.0.1"
edition = "2018"
description = "A cli tool build sewup project to a deploy wasm"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.40"
hex = "0.4.3"
toml = "0.5.8"
serde = "1.0"
serde_derive = "1.0"
